version = 0.1
[default.deploy.parameters]
stack_name = "horariu-app"
s3_bucket = "horariu-app-deployment-bucket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
