AWSTemplateFormatVersion: 2010-09-09
Description: >-
  api-test
Transform:
- AWS::Serverless-2016-10-31

Resources:

  HorariuApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/server.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 100
      Description: Horariu API to handle all the requests
      # Check if we need policies to run the function in AWS
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        DB_HOST: ""
        DB_PORT: ""
        DB_USER: ""
        DB_PASSWORD: ""
        DB_NAME: ""
        JWT_SECRET: ""
