name: API Quality Check

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches-ignore:
      - main
    paths:
      - 'backend/**'

concurrency:
  group: ci-api-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund
        working-directory: backend

      - name: Lint code
        run: npm run lint
        working-directory: backend

      - name: Build
        run: npm run build
        working-directory: backend

      - name: Run tests
        run: npm test
        working-directory: backend